name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      - name: Install necessary system libraries for Playwright
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwoff2dec1 libvpx7 libevent-2.1-7 libopus0 \
            libgstallocators-1.0-0 libgstapp-1.0-0 libgstpbutils-1.0-0 \
            libgstaudio-1.0-0 libgsttag-1.0-0 libgstvideo-1.0-0 \
            libgstgl-1.0-0 libgstcodecparsers-1.0-0 \
            libgstfft-1.0-0 libharfbuzz-icu0 libhyphen0 \
            libmanette-0.2-0 libflite1 libflite-usenglish1 \
            libflite-cmu-grapheme-lang1 libflite-cmu-grapheme-lex1 \
            libflite-cmu-indic-lang1 libflite-cmu-indic-lex1 \
            libflite-cmulex1 libflite-cmu-time-awb \
            libflite-cmu-us-awb1 libflite-cmu-us-kal16 \
            libflite-cmu-us-kal1 libflite-cmu-us-rms1 \
            libflite-cmu-us-slt1 libgles2 libx264-155

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Set up Environment Variables
        env:
          APP_USERNAME: ${{ secrets.APP_USERNAME }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
        run: echo "APP_USERNAME=$APP_USERNAME" >> .env && echo "APP_PASSWORD=$APP_PASSWORD" >> .env

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload Playwright report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30