name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      - name: Install necessary system libraries for Playwright
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwoff2-3 \
            libx264-160

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Set up Environment Variables
        env:
          APP_USERNAME: ${{ secrets.APP_USERNAME }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
        run: echo "APP_USERNAME=$APP_USERNAME" >> .env && echo "APP_PASSWORD=$APP_PASSWORD" >> .env

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload Playwright report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30