name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      - name: Install necessary system libraries for Playwright
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwoff2-dev \
            libx264-dev \
            wget

          # Manually install libx264 if not available
          if ! dpkg -s libx264-dev; then
            wget http://ftp.debian.org/debian/pool/main/x/x264/libx264-160_0.160.3011+g440b0f1-2_amd64.deb
            sudo dpkg -i libx264-160_0.160.3011+g440b0f1-2_amd64.deb
            sudo apt-get install -f
          fi

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Set up Environment Variables
        env:
          APP_USERNAME: ${{ secrets.APP_USERNAME }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
        run: echo "APP_USERNAME=$APP_USERNAME" >> .env && echo "APP_PASSWORD=$APP_PASSWORD" >> .env

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload Playwright report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30